# Minimal Netlify Configuration for CoveTalks
# Place this file in the root of your repository

[build]
  base = "COVETALKSMAIN/covetalks-nextjs"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"